[package]
name = "git"
version = "0.1.0"
edition = "2021"

[dependencies]
duct = { git = "https://github.com/happenslol/duct.rs", branch = "add-stderr-reader" }
thiserror = "1.0.31"
log = "0.4.17"
console = "0.15.0"
threadpool = "1.8.1"
