tab_spaces = 2

# condense_wildcard_suffixes = true
# fn_single_line = true
# format_code_in_doc_comments = true
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
# wrap_comments = true
